services:
    node-app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile_node
        container_name: node-app
        hostname: node-app
        restart: always
        networks:
            - tech-network
        env_file:
            - .env
        tty: true
        ports:
            - "3000:3000"
        depends_on:
            - mongo
        environment:
            MONGO_URI: mongodb://admin:secret@mongo:27017/database    

    mongo:
        image: mongo:latest
        container_name: mongodb
        restart: always
        ports:
        - "27017:27017"        
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: secret
        volumes:
            - mongo_data:/data/db
        networks:
            - tech-network

    mongo-express:
        image: mongo-express:latest
        container_name: mongo-express
        restart: always
        ports:
            - "8081:8081"
        networks:
            - tech-network
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: secret
            ME_CONFIG_MONGODB_SERVER: mongo

networks:
    tech-network:
        driver: bridge

volumes:
    mongo_data:
